version: '3'

services:
  db-suppliers:
    container_name: db-suppliers
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=onparty-suppliers
    networks:
      - net
 
networks:
  net:
