version: '3'

services:
  front-end:
    image: nginx
    ports:
      - '8084:80'
    volumes: 
      - ./front-microservicos:/usr/share/nginx/html/
      - ./front-microservicos/nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - net

  rws-onparty-middleware:
      container_name: rws-onparty-middleware
      build:
        context: ../..
        dockerfile: ./rws-onparty-middleware/Dockerfile
      image: onparty/middleware-img
      ports:
        - '8081:8081'
      deploy:
        restart_policy:
            condition: on-failure
            delay: 5s
      networks:
        - net

networks:
  net:
