# Use postgres/example user/password credentials
version: '3.1'

services:

  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS firstDB; CREATE DATABASE IF NOT EXISTS secondDB;'
         --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "