version: '3'

services:
  #visualizador:
  #  image: dockersamples/visualizer
  #  volumes:
  #  - "/var/run/docker.sock:/var/run/docker.sock"
  #  ports:
  #  - 8079:8080
  #  deploy:
  #    placement:
  #      constraints:
  #        - node.role == manager
  front-end:
    image: nginx
    ports:
      - '8084:80'
    volumes: 
      - "C:/Users/Zupper/Desktop/Projects/on-paty/front-microservicos:/usr/share/nginx/html/"
      - "C:/Users/Zupper/Desktop/Projects/on-paty/front-microservicos/nginx.conf:/etc/nginx/conf.d/default.conf"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - net
networks: 
    net: